# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyWeather
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'GSMessages'
    pod 'BulletinBoard'

  target 'MyWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyWeatherUITests' do
    # Pods for testing
  end

end
